export const ENVIRONMENT = {
	API_ROUTE: "/api",

	HOSTED_UI: "HOSTED UI NOT SET",
	HOSTED_API: "HOSTED API NOT SET",

	STRIPE_KEY: "STRIPE_KEY_NOT_SET",
	STRIPE_WEBHOOK_KEY: "STRIPE_WEBHOOK_KEY_NOT_SET",
	SENDINBLUE_API_KEY: "SENDINBLUE_KEY_NOT_SET",
	LOGSNAG: "LOGSNAG_KEY_NOT_SET",
	REDIS_HOST: "NO_REDIS_HOST",
	REDIS_PASSWORD: "NO_REDIS_PASSWORD",

	

	MYSQL_HOST: "hplsupport.co.uk",
	MYSQL_USER: "hplsupport_user",
	MYSQL_DATABASE: "hplsupport_database",
	MYSQL_PASSWORD: "QbM_rygid2uD",

	MID: "NO_MID",
	SHARED_KEY: "NO_SHARED_KEY"
};
